Fix: NameError exception.
Fix following exception.

embulk bundle /tmp/hoge2
2015-09-17 19:21:53.252 +0900: Embulk v0.7.4
NameError: undefined local variable or method `path' for Embulk:Module
      run at /path/to/.embulk/bin/embulk!/embulk/command/embulk_run.rb:133
    <top> at /path/to/.embulk/bin/embulk!/embulk/command/embulk_main.rb:2
  require at org/jruby/RubyKernel.java:940
   (root) at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:1
    <top> at file:/path/to/.embulk/bin/embulk!/embulk/command/embulk_bundle.rb:55